# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "jekyll", "~> 3.9.5"
gem 'jekyll-feed', "~> 0.17.0"
gem 'jekyll-readme-index', "~> 0.3.0"
gem 'jemoji', "~> 0.13.0"
gem 'webrick'

gem 'wdm', '>= 0.1.0' if Gem.win_platform?

gem 'jekyll-remote-theme'

gem "github-pages", "~> 231", group: :jekyll_plugins

# gem "psych"
# gem "rails"